# Generated by Django 5.1.3 on 2025-01-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uniq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_NAME', models.CharField(max_length=100)),
                ('PRODUCT_CODE', models.CharField(max_length=100)),
                ('PRICE', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=100)),
                ('FOODPRODECT', models.CharField(max_length=100)),
            ],
        ),
    ]
